language: emacs-lisp
sudo: false
env:
  - EMACS_VERSION=25.3
  - EMACS_VERSION=snapshot
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION)
  - make -f emacs-travis.mk install_emacs
script:
  # Run your tests
  - ./run-tests.sh
